name: Readme

on:
  schedule:
    - cron: 0 18 * * *
  push:
    branches:
      - main

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: JasonEtco/rss-to-readme@v1.2.6
        with:
          feed-url: https://attachmentgenie.github.io/blog/index.xml
          readme-section: feed
